SELECT LL.AUTHOR_ID, LL.AUTHOR_NAME, CATEGORY, SUM(TOTAL_SALES) FROM AUTHOR LL
RIGHT JOIN 
(SELECT L.BOOK_ID, CATEGORY, AUTHOR_ID, PRICE * TOTAL AS TOTAL_SALES FROM BOOK L
RIGHT JOIN (SELECT BOOK_ID, SALES_DATE, SUM(SALES) AS TOTAL FROM BOOK_SALES WHERE YEAR(SALES_DATE) = '2022' AND MONTH(SALES_DATE) = '01' GROUP BY BOOK_ID) R
ON L.BOOK_ID = R.BOOK_ID)
RR
ON LL.AUTHOR_ID = RR.AUTHOR_ID
GROUP BY RR.AUTHOR_ID, RR.CATEGORY
ORDER BY RR.AUTHOR_ID ASC, RR.CATEGORY DESC

# SELECT * FROM BOOK