SELECT L.ID, IFNULL(R.CHILD_COUNT, 0) AS CHILD_COUNT FROM ECOLI_DATA L LEFT JOIN (SELECT PARENT_ID AS ID, COUNT(*) AS CHILD_COUNT FROM ECOLI_DATA
GROUP BY PARENT_ID) AS R ON L.ID = R.ID
ORDER BY L.ID

