SELECT L.FLAVOR FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS L_TOTAL FROM FIRST_HALF GROUP BY FLAVOR) L
LEFT JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS R_TOTAL FROM JULY GROUP BY FLAVOR) R
ON L.FLAVOR = R.FLAVOR
GROUP BY L.FLAVOR
ORDER BY SUM(L_TOTAL) + SUM(R_TOTAL) DESC
LIMIT 3;